In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
scardec = pd.read_csv('/home/earthquakes1/homes/Rebecca/phd/stf/data/scardec.csv')
isc = pd.read_csv('/home/earthquakes1/homes/Rebecca/phd/stf/data/isc.csv')
usgs = pd.read_csv('/home/earthquakes1/homes/Rebecca/phd/stf/data/usgs.csv')
sigloch = pd.read_csv('/home/earthquakes1/homes/Rebecca/phd/stf/data/sigloch.csv')
ye = pd.read_csv('/home/earthquakes1/homes/Rebecca/phd/stf/data/ye.csv')

In [4]:
for main in [scardec, ye, isc, sigloch, usgs]:
    for filtered in [scardec, ye, isc, sigloch, usgs]:
        if main is not filtered:
            for i in range(0, len(main)):
                year = main['year'][i]
                month = main['month'][i]
                day = main['day'][i]
                hour = main['hour'][i]
                minute = main['minute'][i]

                filtered = sigloch
                filtered = filtered[filtered['year'] == year]
                if len(filtered) == 0:
                    id = False
                else:
                    filtered = filtered[filtered['month'] == month]
                    if len(filtered) == 0:
                        id = False
                    else:
                        filtered = filtered[filtered['day'] == day]
                        if len(filtered) == 0:
                            id = False
                        else:
                            filtered = filtered[filtered['hour'] == hour]
                            if len(filtered) == 0:
                                id = False
                            else:
                                filtered = filtered[filtered['minute'] == minute]
                                if len(filtered) == 0:
                                    id = False
                                else:
                                    id = filtered['event_id']

In [5]:
combined = pd.DataFrame(columns=['event_id', 'scardec', 'ye', 'isc', 'sigloch', 'usgs'])

In [7]:
m55_catalog = pd.read_csv('/home/earthquakes1/homes/Rebecca/phd/stf/data/combined_m55_catalog.csv', sep = '|')

In [8]:
m55_catalog

,#EventID,Time,Latitude,Longitude,Depth/km,Author,Catalog,Contributor,ContributorID,MagType,Magnitude,MagAuthor,EventLocationName
0,11926233,2025-01-21T11:15:30,-3.7368,151.5823,10.000,"usauto,us",NEIC PDE,us,"usauto6000plel,us6000plel",Mww,5.5,us,"NEW IRELAND REGION, P.N.G."
1,11926190,2025-01-21T06:05:14,-27.4829,-13.4632,10.000,"usauto,us",NEIC PDE,us,"usauto6000pldh,us6000pldh",mb,5.5,us,SOUTHERN MID-ATLANTIC RIDGE
2,11926184,2025-01-21T05:47:51,13.4344,144.3969,137.242,"pt,us,usauto",NEIC PDE,us,"us6000pldf,usauto6000pldf,pt25021000",mww,5.5,us,MARIANA ISLANDS
3,11926033,2025-01-20T16:17:26,23.2338,120.4749,10.000,"us,usauto,at,pt",NEIC PDE,us,"usauto6000pl8h,us6000pl8h,at00sqeal1,pt25020000",mww,6.0,us,TAIWAN
4,11925968,2025-01-20T08:38:43,-11.3327,165.8206,35.000,"usauto,us",NEIC PDE,us,"us6000pl6q,usauto6000pl6q",mww,5.6,us,SANTA CRUZ ISLANDS
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16101,2808110,1990-01-08T19:44:32,52.0105,-169.6001,15.000,ISC,ISC,ISC,380675,mb,5.6,NEIC,"FOX ISLANDS, ALEUTIAN ISLANDS"
16102,2808066,1990-01-07T09:06:43,-15.9527,-74.2840,48.900,ISC,ISC,ISC,380576,mb,5.9,NEIC,NEAR COAST OF PERU
16103,2808053,1990-01-06T21:44:56,-10.6437,92.9744,15.000,ISC,ISC,ISC,380540,mw,5.9,NEIC,SOUTH INDIAN OCEAN
16104,2807962,1990-01-04T05:32:19,-15.4219,-172.9087,42.600,ISC,ISC,ISC,380337,mb,6.4,NEIC,SAMOA ISLANDS REGION
16105,2807919,1990-01-02T20:21:33,13.3906,144.4179,148.500,ISC,ISC,ISC,380214,mw,5.8,NEIC,MARIANA ISLANDS

In [ ]:
#for catalog in [scardec, ye, isc, sigloch, usgs]:
catalogs_list = [scardec, ye, isc, sigloch, usgs]
catalog_names = ['scardec', 'ye', 'isc', 'sigloch', 'usgs']
catalog_ids = ['scardec_name', 'event_id', 'isc_name', 'event_id', 'event_id']
dataset_dict = {}
mag_dict = {}
depth_dict = {}
for catalog, catalog_id, catalog_name, index in zip(catalogs_list, catalog_ids, catalog_names, range(0, len(catalogs_list))):
    for i in range(0, len(catalog)):
        year = int(catalog['year'][i])
        month = int(catalog['month'][i])
        day = int(catalog['day'][i])
        hour = int(catalog['hour'][i])
        minute = int(catalog['minute'][i])

        id = f'{year:04}{month:02}{day:02}_{hour:02}{minute:02}'

        print(catalog[catalog_id][i])

        if id in dataset_dict.keys():
            to_save = dataset_dict[id]
            to_save[index] = str(catalog[catalog_id][i])
        else:
            to_save = ['0', '0', '0', '0', '0']
            to_save[index] = catalog[catalog_id][i]
        dataset_dict[id] = to_save

        if id in mag_dict.keys():
            print('key exists')
            print(mag_dict[id])
            if catalog_name in ['scardec', 'isc', 'sigloch']:
                print('adding new mag')
                mag_name = f'{catalog_name}_magnitude'
                if mag_dict[id] is None:
                    print('in if')
                    mag_dict[id] = [catalog[mag_name][i]]
                else:
                    print('in else')
                    print(mag_dict[id])
                    print(catalog[mag_name][i])
                    to_add = mag_dict[id]
                    to_add.append(catalog[mag_name][i])
                    mag_dict[id] = to_add
        else:
            print('key does not exist')
            if catalog_name in ['scardec', 'isc', 'sigloch']:
                print('adding new mag')
                mag_name = f'{catalog_name}_magnitude'
                mag_dict[id] = [catalog[mag_name][i]]
            else:
                print('adding None')
                mag_dict[id] = None


        if id in depth_dict.keys():
            print('key exists')
            print(depth_dict[id])
            if catalog_name in ['scardec', 'isc', 'sigloch']:
                print('adding new depth')
                depth_name = f'{catalog_name}_depth'
                if depth_dict[id] is None:
                    print('in if')
                    depth_dict[id] = [catalog[depth_name][i]]
                else:
                    print('in else')
                    print(depth_dict[id])
                    print(catalog[depth_name][i])
                    to_add = depth_dict[id]
                    to_add.append(catalog[depth_name][i])
                    depth_dict[id] = to_add
        else:
            print('key does not exist')
            if catalog_name in ['scardec', 'isc', 'sigloch']:
                print('adding new depth')
                depth_name = f'{catalog_name}_depth'
                depth_dict[id] = [catalog[depth_name][i]]
            else:
                print('adding None')
                depth_dict[id] = None

    print(mag_dict)
    print(depth_dict)
for key in mag_dict.keys():
    if mag_dict[key] is not None:
        mag_dict[key] = np.mean(mag_dict[key])
    else:
        mag_dict[key] = None

for key in depth_dict.keys():
    if depth_dict[key] is not None:
        depth_dict[key] = np.mean(depth_dict[key])
    else:
        depth_dict[key] = None

combined = pd.DataFrame.from_dict(dataset_dict, orient='index', columns=['scardec', 'ye', 'isc', 'sigloch', 'usgs'])
combined['mag'] = mag_dict.values()
combined['depth'] = depth_dict.values()

combined.to_csv('/home/earthquakes1/homes/Rebecca/phd/stf/data/combined_scardec_ye_usgs_sigloch_isc_mag_depth.csv')

In [12]:
def myround(x, base=1):
    return base * round(x/base)

In [13]:
catalog = pd.read_csv('/home/earthquakes1/homes/Rebecca/phd/stf/data/combined_m55_catalog.csv', sep = '|')

In [14]:
cols = catalog.columns
column_names = []
for c in cols:
    column_names.append(c.strip().rstrip().lower())
column_names[0] = 'catalog_id'
catalog.columns = column_names

In [15]:
catalog['year'] = catalog.apply(lambda x: x['time'][:4], axis = 1)
catalog['month'] = catalog.apply(lambda x: x['time'][5:7], axis = 1)
catalog['day'] = catalog.apply(lambda x: x['time'][8:10], axis = 1)
catalog['hour'] = catalog.apply(lambda x: x['time'][11:13], axis = 1)
catalog['minute'] = catalog.apply(lambda x: x['time'][14:16], axis = 1)

catalog['event'] = catalog.apply(lambda x: x['year'] + x['month'] + x['day'] + '_' + x['hour'] + x['minute'], axis = 1)

catalog['int_magnitude'] = catalog.apply(lambda x: myround(x['magnitude']), axis = 1)

In [16]:
catalog.drop(columns = ['contributor', 'contributorid', 'magauthor', 'eventlocationname', 'author', 'catalog', 'time'], inplace = True)

In [17]:
catalog = catalog[['event', 'catalog_id', 'year', 'month', 'day', 'hour', 'minute', 'latitude', 'longitude', 'depth/km', 'magnitude', 'int_magnitude', 'magtype']]

In [18]:
catalog

,event,catalog_id,year,month,day,hour,minute,latitude,longitude,depth/km,magnitude,int_magnitude,magtype
0,20250121_1115,11926233,2025,01,21,11,15,-3.7368,151.5823,10.000,5.5,6,Mww
1,20250121_0605,11926190,2025,01,21,06,05,-27.4829,-13.4632,10.000,5.5,6,mb
2,20250121_0547,11926184,2025,01,21,05,47,13.4344,144.3969,137.242,5.5,6,mww
3,20250120_1617,11926033,2025,01,20,16,17,23.2338,120.4749,10.000,6.0,6,mww
4,20250120_0838,11925968,2025,01,20,08,38,-11.3327,165.8206,35.000,5.6,6,mww
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16101,19900108_1944,2808110,1990,01,08,19,44,52.0105,-169.6001,15.000,5.6,6,mb
16102,19900107_0906,2808066,1990,01,07,09,06,-15.9527,-74.2840,48.900,5.9,6,mb
16103,19900106_2144,2808053,1990,01,06,21,44,-10.6437,92.9744,15.000,5.9,6,mw
16104,19900104_0532,2807962,1990,01,04,05,32,-15.4219,-172.9087,42.600,6.4,6,mb
16105,19900102_2021,2807919,1990,01,02,20,21,13.3906,144.4179,148.500,5.8,6,mw